import proguard.gradle.ProGuardTask

buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'com.guardsquare:proguard-gradle:7.7.0'
    }
}

plugins {
    id 'fabric-loom' version '1.11-SNAPSHOT'
    id 'maven-publish'
}

version = project.mod_version + '+' + project.minecraft_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

loom {
    splitEnvironmentSourceSets()

    mods {
        "ghostify" {
            sourceSet sourceSets.main
            sourceSet sourceSets.client
        }
    }

    mixin {
        useLegacyMixinAp = false
    }

    accessWidenerPath = file('src/main/resources/ghostify.accesswidener')
}

repositories {
    // Add repositories to retrieve artifacts from in here.
    // You should only use this when depending on other mods because
    // Loom adds the essential maven repositories to download Minecraft and libraries from automatically.
    // See https://docs.gradle.org/current/userguide/declaring_repositories.html
    // for more information about repositories.
    maven {
        name = 'ParchmentMC'
        url = 'https://maven.parchmentmc.org'
    }
    maven {
        name = 'TerraformersMC' // for ModMenu
        url = "https://maven.terraformersmc.com/releases"
    }
    exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth"
                url = "https://api.modrinth.com/maven"
            }
        }

        filter {
            includeGroup "maven.modrinth"
        }
    }
}

dependencies {
    // To change the versions see the gradle.properties file
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.layered() {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-1.21.8:2025.07.20@zip")
    }
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
    modApi "com.terraformersmc:modmenu:15.0.0-beta.3"

    // for compat
    modCompileOnly "maven.modrinth:skyblocker-liap:v5.7.0+1.21.8"

    compileOnly("org.projectlombok:lombok:1.18.+")
    annotationProcessor("org.projectlombok:lombok:1.18.+")
}

def cleanupJsonFile = { File f ->
    String text = f.getText('UTF-8')
            .replaceAll('(?m)^[ \\t]+', '') // remove leading non-spaces
            .replaceAll('(?m)[ \\t]+$', '') // remove trailing non-spaces
            .replaceAll('(?m)^[ \\t]*\\r?\\n', '') // remove empty lines
            .replaceAll('(?m)^[ \\t]*([{\\[}\\]]\\s*,?)\\s*(?:\\r?\\n|\\z)', '$1') // remove orphan [ { ] } characters
    f.write(text, 'UTF-8')
}

processResources {
    inputs.property "version", project.version
    inputs.property "minecraft_version", project.minecraft_version
    inputs.property "loader_version", project.loader_version
    filteringCharset "UTF-8"

    filesMatching("fabric.mod.json") {
        expand "version": project.version,
                "minecraft_version": project.minecraft_version,
                "loader_version": project.loader_version
    }

    doLast {
        fileTree(dir: file(destinationDir), include: ['**/*.json']).each(cleanupJsonFile)
    }
}

processClientResources {
    doLast {
        fileTree(dir: file(destinationDir), include: ['**/*.vsh', '**/*.fsh']).each { File f ->
            String text = f.getText('UTF-8')
                    .replaceAll('(?s)/\\*.*?\\*/', '') // remove comment blocks
                    .replaceAll('(?m)//.*$', '') // remove comments
                    .replaceAll('(?m)^[ \\t]+', '') // remove leading non-spaces
                    .replaceAll('(?m)[ \\t]+$', '') // remove trailing non-spaces
                    .replaceAll('(?m)^[ \\t]*\\r?\\n', '') // remove empty lines
            f.write(text, 'UTF-8')
        }
        fileTree(dir: file(destinationDir), include: ['**/*.json']).each(cleanupJsonFile)
    }
}

def targetJavaVersion = 21
tasks.withType(JavaCompile).configureEach {
    // ensure that the encoding is set to UTF-8, no matter what the system default is
    // this fixes some edge cases with special characters not displaying correctly
    // see http://yodaconditions.net/blog/fix-for-java-file-encoding-problems-with-gradle.html
    // If Javadoc is generated, this must be specified in that task too.
    it.options.encoding = "UTF-8"
    if (targetJavaVersion >= 10 || JavaVersion.current().isJava10Compatible()) {
        it.options.release.set(targetJavaVersion)
    }
}

java {
    def javaVersion = JavaVersion.toVersion(targetJavaVersion)
    if (JavaVersion.current() < javaVersion) {
        toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }
    // Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
    // if it is present.
    // If you remove this line, sources will not be generated.
    withSourcesJar()
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.archivesBaseName}" }
    }
}

tasks.register('proguard', ProGuardTask) {
    dependsOn tasks.remapJar
    configuration 'proguard-rules.pro'

    optimizationpasses(10)
    verbose()

    if (System.getProperty('java.version').startsWith('1.')) {
        // Before Java 9, the runtime classes were packaged in a single jar file.
        libraryjars "${System.getProperty('java.home')}/lib/rt.jar"
    } else {
        // As of Java 9, the runtime classes are packaged in modular jmod files.
        libraryjars "${System.getProperty('java.home')}/jmods/java.base.jmod", jarfilter: '!**.jar', filter: '!module-info.class'
        //libraryjars "${System.getProperty('java.home')}/jmods/....."
    }
    configurations.runtimeClasspath.incoming.files.each { File file ->
        if (file.isFile() && file.getName().endsWith('.jar')) {
            libraryjars(file.getPath())
        }
    }
    libraryjars loom.files.remappedModCache
    libraryjars loom.files.remapClasspathFile
    libraryjars loom.unmappedModCollection.files.each { File file ->
        if (file.isFile() && file.getName().endsWith('.jar')) {
            libraryjars(file.getPath())
        }
    }
    libraryjars loom.getIntermediaryMinecraftProvider().getMinecraftJarPaths()
    injars tasks.remapJar.outputs.files.singleFile
    outjars(layout.buildDirectory.file("libs/${project.archives_base_name}-${version}-minified.jar"))
}

// configure the maven publication
publishing {
    publications {
        create("mavenJava", MavenPublication) {
            artifactId = project.archives_base_name
            from components.java
        }
    }

    // See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
    repositories {
        // Add repositories to publish to here.
        // Notice: This block does NOT have the same function as the block in the top level.
        // The repositories here will be used for publishing your artifact, not for
        // retrieving dependencies.
    }
}
